name: Build Docker Images (Java, Node, Python)
 
on:
  push:
    branches:
      - main
      - develop
 
jobs:
  docker-build:
    runs-on: ubuntu-latest
 
    strategy:
      matrix:
        include:
          - language: java
            context: java
            dockerfile: java/Dockerfile
            image: java-service
 
          - language: node
            context: node
            dockerfile: node/Dockerfile
            image: node-service
 
          - language: python
            context: python
            dockerfile: python/Dockerfile
            image: python-service
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.KEERTHI_DOCKER}}
          password: ${{ secrets.KEERTHI_KEY}}
      - name: Build and Push Image
        uses: docker/build-push-action@v6
        with:
          context: ./python-app
          file: ./python-app/Dockerfile
          push: true
          tags: ${{ secrets.KEERTHI_DOCKER }}/app:latest
 
      # -------- Dependency Cache --------
      - name: Cache Maven
        if: matrix.language == 'java'
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: maven-${{ hashFiles('java/**/pom.xml') }}
 
      - name: Cache npm
        if: matrix.language == 'node'
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('node/package-lock.json') }}
 
      - name: Cache pip
        if: matrix.language == 'python'
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ hashFiles('python/requirements.txt') }}
 
      # -------- Docker Setup --------
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
 
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
 
      # -------- Image Tags --------
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}-${{ matrix.image }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=branch
            type=sha
 
      # -------- Build & Push --------
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
